/* Command registry, aliases, and AutoCAD-style numeric point input. */
import { parseLength, parsePoint, parseAngleDeg, fmtFtIn } from './format.js';

export const COMMANDS = {
  SELECT:  { aliases: ['SELECT', 'SEL', 'V'],           tool: 'select',  prompt: 'Select objects' },
  PAN:     { aliases: ['PAN', 'H'],                     tool: 'pan',     prompt: 'Pan' },
  LINE:    { aliases: ['LINE', 'L'],                    tool: 'line',    prompt: 'Specify first point' },
  PLINE:   { aliases: ['PLINE', 'POLY', 'P'],           tool: 'poly',    prompt: 'Specify start point' },
  SPLINE:  { aliases: ['SPLINE', 'SPL'],                tool: 'spline',  prompt: 'Specify first control point' },
  ARCSEG:  { aliases: ['ARCSEG', 'PARC'],                tool: 'arcseg',  prompt: 'Tap beside a polyline segment to curve it' },
  MTEXT:   { aliases: ['MTEXT', 'MT', 'NOTE'],           tool: 'mtext',   prompt: 'Drag the column width for the note' },
  RECT:    { aliases: ['RECT', 'RECTANGLE', 'REC'],     tool: 'rect',    prompt: 'Specify first corner' },
  CIRCLE:  { aliases: ['CIRCLE', 'C'],                  tool: 'circle',  prompt: 'Specify center point' },
  ARC:     { aliases: ['ARC', 'A'],                     tool: 'arc',     prompt: 'Specify start point of arc' },
  WALL:    { aliases: ['WALL', 'WL'],                   tool: 'wall',    prompt: 'Specify start of wall' },
  OFFSET:  { aliases: ['OFFSET', 'O'],                  tool: 'offset',  prompt: 'Specify offset distance', numeric: 'distance' },
  TRIM:    { aliases: ['TRIM', 'TR', 'X'],              tool: 'trim',    prompt: 'Select object to trim' },
  EXTEND:  { aliases: ['EXTEND', 'EX', 'E'],            tool: 'extend',  prompt: 'Select object to extend' },
  FILLET:  { aliases: ['FILLET', 'FILLE', 'B'],         tool: 'fillet',  prompt: 'Specify radius', numeric: 'radius' },
  CHAMFER: { aliases: ['CHAMFER', 'CHA', 'N'],          tool: 'chamfer', prompt: 'Specify chamfer distance', numeric: 'distance' },
  MIRROR:  { aliases: ['MIRROR', 'MI', 'I'],            tool: 'mirror',  prompt: 'Select objects to mirror' },
  SCALE:   { aliases: ['SCALE', 'SC', 'G'],             tool: 'scale',   prompt: 'Specify base point', numeric: 'factor' },
  ROTATE:  { aliases: ['ROTATE', 'RO'],                 tool: 'rotate',  prompt: 'Specify base point', numeric: 'angle' },
  MOVE:    { aliases: ['MOVE', 'W'],                    tool: 'move',    prompt: 'Specify base point' },
  COPY:    { aliases: ['COPY', 'CO', 'U'],              tool: 'copy',    prompt: 'Specify base point' },
  ARRAY:   { aliases: ['ARRAY', 'AR', 'Y'],             tool: 'array',   prompt: 'Select objects to array' },
  JOIN:    { aliases: ['JOIN', 'J'],                    tool: 'join',    prompt: 'Select objects to join' },
  HATCH:   { aliases: ['HATCH', 'HATCHING', 'K'],       tool: 'hatch',   prompt: 'Pick internal point or polyline' },
  DIM:     { aliases: ['DIM', 'DIMLIN', 'D'],           tool: 'dim',     prompt: 'Specify first extension origin' },
  DIMALI:  { aliases: ['DIMALIGNED', 'DIMALI', 'DAL'],  tool: 'dimali',  prompt: 'Specify first extension origin' },
  DIMCON:  { aliases: ['DIMCONTINUE', 'DIMCONT', 'DCO'], tool: 'dimcont', prompt: 'Specify next extension origin' },
  DIMBASE: { aliases: ['DIMBASELINE', 'DIMBASE', 'DBA'], tool: 'dimbase', prompt: 'Specify next extension origin' },
  TEXT:    { aliases: ['TEXT', 'T'],                    tool: 'text',    prompt: 'Specify start point of text' },
  ELLIPSE: { aliases: ['ELLIPSE', 'EL'],                tool: 'ellipse', prompt: 'Specify center of ellipse' },
  REVCLOUD:{ aliases: ['REVCLOUD', 'RC', 'CLOUD'],      tool: 'cloud',   prompt: 'Specify start of revision cloud' },
  LEADER:  { aliases: ['LEADER', 'LE', 'MLD'],          tool: 'leader',  prompt: 'Specify first leader point' },
  DIMRAD:  { aliases: ['DIMRADIUS', 'DIMRAD', 'DRA'],   tool: 'dimrad',  prompt: 'Select circle or arc' },
  DIMDIA:  { aliases: ['DIMDIAMETER', 'DIMDIA', 'DDI'], tool: 'dimdia',  prompt: 'Select circle' },
  DIMANG:  { aliases: ['DIMANGULAR', 'DIMANG', 'DAN'],  tool: 'dimang',  prompt: 'Specify first angle endpoint' },
  STRETCH: { aliases: ['STRETCH', 'ST'],                tool: 'stretch', prompt: 'Specify first corner of stretch box' },
  MATCH:   { aliases: ['MATCHPROP', 'MA', 'MATCH'],     tool: 'match',   prompt: 'Select source object' },
  AREA:    { aliases: ['AREA', 'AA'],                   tool: 'area',    prompt: 'Select object for area' },
  LIST:    { aliases: ['LIST', 'LI'],                   tool: 'list',    prompt: 'Select object to list' },
  ID:      { aliases: ['ID'],                           tool: 'id',      prompt: 'Specify point' },
  SCHEDULE:{ aliases: ['SCHEDULE', 'SCH', 'TABLE'],     tool: 'schedule',prompt: 'Specify insertion point of schedule' },
  IMAGE:   { aliases: ['IMAGE', 'IMG', 'TRACE'],        tool: 'image',   prompt: 'Specify first corner of image' },
  CALIB:   { aliases: ['CALIBRATE', 'CAL'],             tool: 'calibrate', prompt: 'Specify first calibration point' },
  CLEANUP: { aliases: ['CLEANUP', 'CLN'],               tool: null,     action: 'cleanup' },
  SVG:     { aliases: ['SVG'],                          tool: null,     action: 'svg' },
  GRID:    { aliases: ['GRID', 'GR'],                   tool: 'grid',    prompt: 'Specify first corner of grid' },
  XLINE:   { aliases: ['XLINE', 'XL', 'CONSTRUCTION'],  tool: 'xline',   prompt: 'Specify first point of construction line' },
  ARRPOL:  { aliases: ['ARRAYPOLAR', 'ARP', 'POLAR'],   tool: 'arraypolar', prompt: 'Specify center of polar array' },
  OVERKILL:{ aliases: ['OVERKILL', 'OV'],               tool: null,     action: 'overkill' },
  ROOMS:   { aliases: ['ROOMS', 'ROOMDETECT'],          tool: null,     action: 'rooms' },
  TAKEOFF: { aliases: ['TAKEOFF', 'TO', 'QTO'],         tool: null,     action: 'takeoff' },
  LAYISO:  { aliases: ['LAYISO', 'ISO'],                tool: null,     action: 'layiso' },
  LAYUNISO:{ aliases: ['LAYUNISO', 'UNISO'],            tool: null,     action: 'layuniso' },
  OPEN:    { aliases: ['OPEN', 'OP'],                   tool: null,     action: 'open' },
  DXFIN:   { aliases: ['DXFIN', 'INSERTDXF'],           tool: null,     action: 'dxfin' },
  MEASURE: { aliases: ['MEASURE', 'DIST', 'M'],         tool: 'measure', prompt: 'Specify first point' },
  ERASE:   { aliases: ['ERASE', 'ER', 'Q'],             tool: 'erase',   prompt: 'Select objects to erase' },
  SYMBOL:  { aliases: ['SYMBOL', 'BLOCK', 'S', 'INSERT'], tool: 'symbol', prompt: 'Specify insertion point' },
  EXPLODE: { aliases: ['EXPLODE', 'XP'],                 tool: null,     action: 'explode' },
  FLIP:    { aliases: ['FLIP'],                          tool: null,     action: 'flip' },
  ZFIT:    { aliases: ['ZOOMFIT', 'ZFIT'],              tool: null,     action: 'zoomfit' },
  SHEETSET:{ aliases: ['SHEETSET', 'SS', 'SHEETS'],     tool: null,     action: 'sheetset' },
  XREF:    { aliases: ['XREF', 'XR', 'XA', 'ATTACH'],   tool: null,     action: 'xref' },
  BIND:    { aliases: ['BIND'],                         tool: null,     action: 'bind' },
  SECTION: { aliases: ['SECTION', 'SE', 'CUT'],         tool: 'section', prompt: 'Specify first point of cutting plane' },
  DETAIL:  { aliases: ['DETAIL', 'DET'],                tool: 'detail',  prompt: 'Specify first corner of detail window' },
  FCF:     { aliases: ['FCF', 'GDT', 'TOL'],            tool: 'fcf',     prompt: 'Specify feature, then frame location' },
  DATUM:   { aliases: ['DATUM', 'DAT'],                 tool: 'datum',   prompt: 'Specify datum origin' },
  SF:      { aliases: ['FINISH', 'SF', 'SURF'],         tool: 'finish',  prompt: 'Specify surface-finish origin' },
  V3D:     { aliases: ['3D', 'V3D', 'VIEW3D', 'ORBIT'], tool: null,     action: 'view3d' },
  PLAN:    { aliases: ['PLAN', 'V2D', '2D'],            tool: null,     action: 'view2d' },
  HEIGHT:  { aliases: ['HEIGHT', 'HT', 'STORY'],        tool: null,     action: 'height' },
  DWGOUT:  { aliases: ['DWGOUT', 'SAVEASDWG'],          tool: null,     action: 'dwgout' },
  CHOR:    { aliases: ['HOR', 'CHOR'],                  tool: null,     action: 'con:horizontal' },
  CVERT:   { aliases: ['VERT', 'CVERT'],                tool: null,     action: 'con:vertical' },
  CPAR:    { aliases: ['PAR', 'CPAR'],                  tool: null,     action: 'con:parallel' },
  CPERP:   { aliases: ['PERP', 'CPERP'],                tool: null,     action: 'con:perpendicular' },
  CEQ:     { aliases: ['CEQ', 'EQUAL'],                 tool: null,     action: 'con:equal' },
  COIN:    { aliases: ['COIN', 'COINCIDENT'],           tool: null,     action: 'con:coincident' },
  CDIST:   { aliases: ['CDIST', 'CLEN'],                tool: null,     action: 'con:distance' },
  CRAD:    { aliases: ['CRAD'],                         tool: null,     action: 'con:radius' },
  CTAN:    { aliases: ['CTAN'],                         tool: null,     action: 'con:tangent' },
  CFIX:    { aliases: ['CFIX', 'ANCHOR'],               tool: null,     action: 'con:fix' },
  CSOLVE:  { aliases: ['CSOLVE', 'SOLVE'],              tool: null,     action: 'csolve' },
  CDEL:    { aliases: ['CDEL', 'UNCONSTRAIN'],          tool: null,     action: 'cdel' },
  BHATCH:  { aliases: ['BHATCH', 'HATCHI'],             tool: null,     action: 'bhatch' },
  UNION:   { aliases: ['UNION', 'BUNION'],              tool: null,     action: 'bool:union' },
  SUBTRACT:{ aliases: ['SUBTRACT', 'BSUB'],             tool: null,     action: 'bool:difference' },
  INTERSECT:{ aliases: ['INTERSECT', 'BINT'],           tool: null,     action: 'bool:intersect' },
  BXOR:    { aliases: ['BXOR', 'EXCLUSIVE'],            tool: null,     action: 'bool:xor' },
  LAYSAVE: { aliases: ['LAYSAVE', 'LSAVE'],             tool: null,     action: 'laysave' },
  LAYREST: { aliases: ['LAYREST', 'LRESTORE'],          tool: null,     action: 'layrest' },
  LAYDEL:  { aliases: ['LAYDEL'],                       tool: null,     action: 'laydel' },
  PLOTSTYLE:{ aliases: ['PLOTSTYLE', 'CTB'],            tool: null,     action: 'plotstyle' },
  VPTWIST: { aliases: ['VPTWIST', 'TWIST', 'VPROTATE'],  tool: null,     action: 'vptwist' },
  VPCLIP:  { aliases: ['VPCLIP', 'CLIPVIEW'],           tool: null,     action: 'vpclip' },
  EXTRUDE: { aliases: ['EXTRUDE', 'EXT'],               tool: null,     action: 'extrude3d' },
  REVOLVE: { aliases: ['REVOLVE', 'REV'],               tool: null,     action: 'revolve3d' },
  LOFT:    { aliases: ['LOFT'],                         tool: null,     action: 'loft3d' },
  SOLIDCLR:{ aliases: ['SOLIDCLR', 'CLEARSOLIDS'],      tool: null,     action: 'clearsolids' }
};

const ALIAS = {};
for (const [name, c] of Object.entries(COMMANDS)){
  for (const a of c.aliases) ALIAS[a] = name;
}

export function lookupCommand(s){
  if (!s) return null;
  const k = String(s).trim().toUpperCase();
  const name = ALIAS[k];
  if (!name) return null;
  return { name, ...COMMANDS[name] };
}

export function defaultPrompt(tool, state){
  const r = state && state.filletR != null ? state.filletR : 0.5;
  const d = state && state.chamferD != null ? state.chamferD : 0.5;
  const off = state && state.offsetDist != null ? state.offsetDist : 0.5;
  const map = {
    fillet:  'FILLET Specify radius <' + fmtFtIn(r) + '>:',
    chamfer: 'CHAMFER Specify distance <' + fmtFtIn(d) + '>:',
    offset:  'OFFSET Specify distance <' + fmtFtIn(off) + '>:',
    scale:   'SCALE Specify scale factor <1.0>:',
    rotate:  'ROTATE Specify rotation angle <90>:',
    line:    'LINE Specify next point:',
    poly:    'PLINE Specify next point:',
    spline:  'SPLINE Specify next control point:',
    mtext:   'MTEXT Specify opposite corner of the column:',
    rect:    'RECT Specify opposite corner:',
    circle:  'CIRCLE Specify radius:',
    arc:     'ARC Specify next point:',
    wall:    'WALL Specify next point:',
    dim:     'DIM Specify second extension origin:',
    dimali:  'DIMALIGNED Specify second origin:',
    dimcont: 'DIMCONTINUE Specify next origin:',
    dimbase: 'DIMBASELINE Specify next origin:',
    move:    'MOVE Specify destination:',
    copy:    'COPY Specify destination:',
    mirror:  'MIRROR Specify second point of mirror line:',
    array:   'ARRAY Specify columns,rows,colDist,rowDist:',
    hatch:   'HATCH Pick a closed shape or internal point:',
    measure: 'MEASURE Specify second point:',
    text:    'TEXT Specify start point:',
    select:  'SELECT objects:',
    trim:    'TRIM Select object to trim:',
    extend:  'EXTEND Select object to extend:',
    erase:   'ERASE Select object:',
    join:    'JOIN Select objects and press Enter:',
    symbol:  'INSERT Specify insertion point:',
    ellipse: 'ELLIPSE Specify opposite corner:',
    cloud:   'REVCLOUD Specify next point:',
    leader:  'LEADER Specify next point:',
    dimrad:  'DIMRADIUS Select circle or arc:',
    dimdia:  'DIMDIAMETER Select circle:',
    dimang:  'DIMANGULAR Specify next point:',
    stretch: 'STRETCH Specify displacement:',
    match:   'MATCHPROP Select destination object:',
    area:    'AREA Select a closed object:',
    list:    'LIST Select object:',
    id:      'ID Specify point:',
    schedule:'SCHEDULE Specify insertion point:',
    image:   'IMAGE Specify opposite corner:',
    calibrate: 'CALIBRATE Specify second point:',
    grid:    'GRID Specify opposite corner:',
    xline:   'XLINE Specify second point:',
    arraypolar: 'ARRAYPOLAR Specify center of array:',
    section: 'SECTION Specify second point of cutting plane:',
    detail:  'DETAIL Specify opposite corner:',
    fcf:     'FCF Specify frame location:',
    datum:   'DATUM Specify origin:',
    finish:  'FINISH Specify origin:'
  };
  return map[tool] || ((tool || 'Command') + ':');
}

export { parseLength, parsePoint, parseAngleDeg };
